# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.12-slim

# Install dependencies
WORKDIR /app
COPY pyproject.toml uv.lock .
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
       gcc libssl-dev build-essential \
    && pip install --no-cache-dir mcp[cli]==1.9.0 bleach markdown httpx \
    && rm -rf /var/lib/apt/lists/*

# Copy source code
COPY main.py .

# Expose no HTTP port since stdio transport

# Default command
CMD ["python", "main.py"]
